version: "3"
services:
  basteva:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 2
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: basteva
        POSTGRES_DB: basteva
        POSTGRES_HOST: postgres
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/basteva
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: basteva
      POSTGRES_DB: basteva
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  nginx:
    image: nginx
    depends_on:
      - basteva
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
