"""empty message

Revision ID: ac35dd8b89c5
Revises: 4c8ee9631f61
Create Date: 2020-11-18 22:06:59.710546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac35dd8b89c5'
down_revision = '4c8ee9631f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('fqdn', sa.Text(), nullable=True))
    op.add_column('instance', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('instance', sa.Column('ssh_key', sa.Text(), nullable=True))
    op.add_column('instance', sa.Column('user', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'user')
    op.drop_column('instance', 'ssh_key')
    op.drop_column('instance', 'password')
    op.drop_column('instance', 'fqdn')
    # ### end Alembic commands ###
